name: task_weather_app
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  geolocator: ^9.0.2
  meta: ^1.15.0
  bloc: ^9.0.0


dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/png/
  
